server:
  port: 18771

hazelcastClient:
  systemInterface:
    imdgInterface:
      imdgManager:
        host:
          addresses: 127.0.0.1
      imdgWatcher:
        batch:
          start: 'C:\workspace\Sample Codes\Hazelcast\Server\hazelcast-3.12.9\bin\start.bat'
          stop: 'C:\workspace\Sample Codes\Hazelcast\Server\hazelcast-3.12.9\bin\stop.bat'
        server:
          port : 5701